# 1. 인스턴스 프로파일에서 role 분리
- name: Detach role from EC2 Instance Profile
  amazon.aws.iam_instance_profile:
    name: "{{ prefix }}-app-instance-profile"
    role: ""

# 2. EC2 인스턴스 프로파일 삭제
- name: Remove EC2 Instance Profile
  amazon.aws.iam_instance_profile:
    name: "{{ prefix }}-app-instance-profile"
    state: absent

# 3. CodeDeploy 서비스 역할 삭제
- name: Remove CodeDeploy Service Role
  amazon.aws.iam_role:
    name: "{{ prefix }}-codedeploy-service-role"
    state: absent

# 4. APP EC2 역할 삭제
- name: Remove APP EC2 Role
  amazon.aws.iam_role:
    name: "{{ prefix }}-app-ec2-role"
    state: absent