---
# 1. APP 인스턴스 프로파일에서 Role 분리
- name: Detach role from APP Instance Profile
  amazon.aws.iam_instance_profile:
    name: "{{ prefix }}-app-instance-profile"
    role: ""
  ignore_errors: yes

# 2. Jenkins 인스턴스 프로파일에서 Role 분리
- name: Detach role from Jenkins Instance Profile
  amazon.aws.iam_instance_profile:
    name: "{{ prefix }}-jenkins-instance-profile"
    role: ""
  ignore_errors: yes

# 3. APP 인스턴스 프로파일 삭제
- name: Remove APP Instance Profile
  amazon.aws.iam_instance_profile:
    name: "{{ prefix }}-app-instance-profile"
    state: absent
  ignore_errors: yes

# 4. Jenkins 인스턴스 프로파일 삭제
- name: Remove Jenkins Instance Profile
  amazon.aws.iam_instance_profile:
    name: "{{ prefix }}-jenkins-instance-profile"
    state: absent
  ignore_errors: yes

# 5. CodeDeploy 서비스 역할 삭제
- name: Remove CodeDeploy Service Role
  amazon.aws.iam_role:
    name: "{{ prefix }}-codedeploy-service-role"
    state: absent
  ignore_errors: yes

# 6. APP EC2 역할 삭제
- name: Remove APP EC2 Role
  amazon.aws.iam_role:
    name: "{{ prefix }}-app-ec2-role"
    state: absent
  ignore_errors: yes

# 7. Jenkins EC2 역할 삭제
- name: Remove Jenkins EC2 Role
  amazon.aws.iam_role:
    name: "{{ prefix }}-jenkins-ec2-role"
    state: absent
  ignore_errors: yes